org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true

# Identity
mod_name=VS2 Utilities
mod_id=vsutil
mod_version=1.0.0-alpha
mod_description=Miscellaneous utility features for Valkyrien Skies 2.

mod_license=MIT
mod_author=kawaiicakes
homepage=https://www.curseforge.com/members/kawaiicakes/projects
sources=https://github.com/kawaiicakes/VSUtil
issue_tracker=https://github.com/kawaiicakes/VSUtil/issues

enabled_platforms=fabric,forge
archives_base_name=vsutil
maven_group=io.github.kawaiicakes
loader_platform=Common

# Dependencies
minecraft_version=1.19.2

fabric_loader_version=0.14.24
fabric_api_version=0.76.1+1.19.2

forge_version=1.19.2-43.3.0

kff_version=3.12.0

vs2_version=2.1.2-beta.1+a04911c932
vs_core_version=1.1.0+b19b27c4a4

mixin_extras_version=0.2.0

# Accessing VS repo/Maven publishing. Leave this because stripping the credentials block causes problems
vs_maven_url=
vs_maven_username=
vs_maven_password=

# For release builds
curse_api_key=
curse_project_id=
modrinth_api_key=
modrinth_project_id=
