architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/vsutil.accesswidener")
}

repositories {
    // mavens for Create Fabric and dependencies
    maven { url = "https://mvn.devos.one/releases" } // Porting Lib releases
    maven { url = "https://mvn.devos.one/snapshots" } // Create and several dependencies
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // Forge Config API Port

    maven { // Fabric ASM for Porting Lib
        url = "https://jitpack.io/"
        content { includeGroupAndSubgroups("com.github") }
    }

    maven { url = "https://maven.shedaniel.me" } // Cloth Config, REI
    maven { url = "https://maven.blamejared.com" } // JEI

    maven { url = "https://api.modrinth.com/maven" } // LazyDFU
    maven { url = "https://maven.terraformersmc.com/releases" } // Mod Menu, EMI
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:$mixin_extras_version"))

    // Valkyrien Skies 2
    modCompileOnly("org.valkyrienskies:valkyrienskies-120-common:${rootProject.vs2_version}")

    // VS Core
    compileOnly("org.valkyrienskies.core:api:${rootProject.vs_core_version}")
    compileOnly("org.valkyrienskies.core:api-game:${rootProject.vs_core_version}")
    compileOnly("org.valkyrienskies.core:util:${rootProject.vs_core_version}")
    compileOnly("org.valkyrienskies.core:impl:${rootProject.vs_core_version}")

    modCompileOnly("com.simibubi.create:create-fabric-$minecraft_version:$create_fabric_version")

    modCompileOnly "curse.maven:create-big-cannons-646668:6064373"
    modCompileOnly "curse.maven:create-clockwork-807792:5580458"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            groupId = "io.github.kawaiicakes.vsutil"
            version = project.version
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
}